### ISSUE TITLE
ASCII characters not enforced in product SeName/slug

### ISSUE THREAD

**Issue by dctremblay** [grandnode/grandnode#670]
When a product does have a SeName/slug with non-ASCII character, when  previewing the product page, a 500 error page is shown. The stack trace can be found in System -> Log

**Expected behaviour**

When creating a product with an accent in the product name, the auto generated SeName must have its non-ASCII characters converted to ASCII equivalent, or stripped.

But also, either :

- non-ASCII characters must converted to ASCII equivalent on save
- show form validation error to the user when attempting to save product SeName containing a non-ASCII character

Example :

- é -> e
- à -> a
- ù -> u
- ë -> e
- an so on ..

**Stack trace**

```
System.InvalidOperationException: Invalid non-ASCII or control character in header: 0x00E9
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.ThrowInvalidHeaderCharacter(Char ch)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.ValidateHeaderValueCharacters(StringValues& headerValues)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseHeaders.SetValueFast(String key, StringValues& value)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.Microsoft.AspNetCore.Http.IHeaderDictionary.set_Item(String key, StringValues value)
   at Microsoft.AspNetCore.Http.Internal.DefaultHttpResponse.Redirect(String location, Boolean permanent)
   at Microsoft.AspNetCore.Mvc.Infrastructure.RedirectResultExecutor.ExecuteAsync(ActionContext context, RedirectResult result)
   at Microsoft.AspNetCore.Mvc.RedirectResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultAsync(IActionResult result)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResultFilterAsync[TFilter,TFilterAsync]()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Grand.Framework.Infrastructure.WorkContextMiddleware.InvokeAsync(HttpContext context, IWorkContext workContext) in D:\GrandnodeGit\grandnode\Grand.Framework\Infrastructure\WorkContextMiddleware.cs:line 45
   at Grand.Framework.Infrastructure.StoreContextMiddleware.InvokeAsync(HttpContext context, IStoreContext storeContext) in D:\GrandnodeGit\grandnode\Grand.Framework\Infrastructure\StoreContextMiddleware.cs:line 40
   at Grand.Services.Authentication.AuthenticationMiddleware.Invoke(HttpContext context) in D:\GrandnodeGit\grandnode\Grand.Services\Authentication\AuthenticationMiddleware.cs:line 81
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Grand.Core.Http.InstallUrlMiddleware.Invoke(HttpContext context, IWebHelper webHelper) in D:\GrandnodeGit\grandnode\Grand.Core\Http\InstallUrlMiddleware.cs:line 48
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at NetEscapades.AspNetCore.SecurityHeaders.SecurityHeadersMiddleware.Invoke(HttpContext context) in C:\projects\netescapades-aspnetcore-securityheaders\src\NetEscapades.AspNetCore.SecurityHeaders\SecurityHeadersMiddleware.cs:line 96
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
```

**Comment by PatrykPorabik** [comment]
I've tried to simulate this on our development enviroment and I'm not able to get this error. Can you tell me step by step with invalid example, how to simulate it?

**Comment by dctremblay** [comment]
Here's what I've done to cross this bug :

1. Deploy GN on DigitalOcean official GN image
    - Ubuntu 18.04
    - .NET Core 2.2.301
    - nginx 1.14.0
2. Add a new product having a Latin accent in its title (éàë...)
3. Save (slug will be then generated)
3. Try to preview page
4. Error 500 with stack trace in logs

**Comment by PatrykPorabik** [comment]
Even on our demo I'm not able to simulate this issue. Can you try to show it on https://demo.grandnode.com?

**Comment by dctremblay** [comment]
Thanks for your help.

That's right, cannot reproduce on demo myself too.

What .NET Core 3 is the demo running on ?

Maybe it is the DigitalOcean image which is broken ?

**Comment by PatrykPorabik** [comment]
The demo is running on .NET Core 2.2. I can check the image again, but I'm not sure if it's the problem.

**Comment by dctremblay** [comment]
Please keep ticket open in case I find a way to manually trigger that bug

**Comment by PatrykPorabik** [comment]
I can confirm, that I've checked the DigitalOcean image and I wasn't able to simulate this issue. So it's something strongly related with your settings or server.

**Comment by sergey-messer** [comment]
It is happen me also.
For reproduce you have to setup multilanguage site with language code in url.
Set up SEO friendly page name contains no ASCII charters.
It happen when redirecting to localized url (with language code) 
Location header contains non-ASCII.
This bug was in NopCommerce and fixed by Custom Redirect Executor with UrlEncoding before redirect.
Fixed Custom  redirect executor has been migrated to GrandNode also, but not work. I tried debug it but code is not running

**Comment by sergey-messer** [comment]
For reproduce go to
https://greenfieldflowers.co.il/en/digital-downloads

And try change language to Hebrew

**Comment by PatrykPorabik** [comment]
Yes, I got it, finally I was able to simulate it. Thanks for clues Sergey.

**Comment by sergey-messer** [comment]
Fix does not work.
I get "too many redirections" exception.
My enviroment:
Two language site.
Search engine friendly page name in english for english and in non-Ascii for second language (Same category page)

**Comment by dctremblay** [comment]
@sergey-messer  Yep the fix I've done does not solve the problem at the source.

I have found that by enabling the feature that convert slugs to ASCII characters, it fixed the problem, but now for example Hebrew wouldn't work at all in that setup.

The patch sets specific config during installation, so what you want to do is to manually change the config key through admin.

If you want to give it a try, search for `ConvertNonWesternChars` config key and set it to true. Worked well to replace french accents characters with ASCII equivalent but I do not think this would work with hebrew.

**Comment by KrzysztofPajak** [comment]
@sergey-messer Is it works correctly when changed the settings (ConvertNonWesternChars) ?

**Comment by sergey-messer** [comment]
Yes I know about ConvertNonWesternChars and it was true.
My problem is when i update several time SEO slug I have multiple entries in table UrlRecord with IsActive false and one (last) IsActive=true.

But UrlRecordService (GetBySlug and  GetBySlugCached functions) run select from this table with wrong OrderBy: 

            var query = from ur in _urlRecordRepository.Table
                        where ur.Slug == slug
                        orderby ur.IsActive
                        select ur;
            return await query.FirstOrDefaultAsync();
When we have Slug IsActive=false it is First with ASC ordering.

I think it have to be 
            var query = from ur in _urlRecordRepository.Table
                        where ur.Slug == slug
                        orderby ur.IsActive descending
                        select ur;
            return await query.FirstOrDefaultAsync();
DESC ordering.
I removed all slugs with IsActive=false and now all work very well.

Thank you

**Comment by PatrykPorabik** [comment]
I think it's solved after last commit. Look at it here: https://github.com/grandnode/grandnode/commit/21a56f59a2dfba4f05647297574098a5c47239ab
